[package]
name = "audact"
version = "0.1.0"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shockham/audact"
homepage = "https://github.com/shockham/audact"
documentation = "https://docs.rs/audact"
description = "Simple synth and sequencing lib"

[dependencies]
futures = "0.1.1"
cpal = "0.4.5"
